[package]
name = "awesomepossum212/nametag-plus"
version = "1.0.0-alpha"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A performant, module and accessible system for nametags"
license = "MIT"

[dependencies]
Signal = "quenty/signal@2.0.0-canary"